import os
import shutil
import uuid
import subprocess
import json
from fastapi import APIRouter, UploadFile, File, HTTPException, Depends
from pathlib import Path
from sqlalchemy.orm import Session
from database import get_db
from models import Job
from utils.freecad_env import find_freecad_python

router = APIRouter()

UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

MAX_FILE_SIZE = 100 * 1024 * 1024  # 100 MB
SUBPROCESS_TIMEOUT = 120  # seconds

# 假设 backend 运行目录下有 scripts/freecad_processor.py
PROCESSOR_SCRIPT = Path("scripts/freecad_processor.py").absolute()

@router.post("/upload/")
async def upload_step_file(file: UploadFile = File(...), db: Session = Depends(get_db)):
    if not (file.filename.lower().endswith(".step") or file.filename.lower().endswith(".stp")):
        raise HTTPException(status_code=400, detail="仅支持 .step / .stp 格式文件")

    # 文件大小校验
    contents = await file.read()
    if len(contents) > MAX_FILE_SIZE:
        raise HTTPException(status_code=413, detail=f"文件过大 (>{MAX_FILE_SIZE // 1024 // 1024} MB)")
    await file.seek(0)

    job_id = str(uuid.uuid4())
    safe_filename = f"{job_id}_{file.filename}"
    file_path = UPLOAD_DIR / safe_filename
    output_dir = UPLOAD_DIR / job_id
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        with file_path.open("wb") as buffer:
            buffer.write(contents)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"保存文件失败: {str(e)}")

    # 写入 Job 记录
    job = Job(id=job_id, filename=file.filename, status="uploaded")
    db.add(job)
    db.commit()

    try:
        freecad_python = find_freecad_python()

        result = subprocess.run(
            [freecad_python, str(PROCESSOR_SCRIPT), "--input", str(file_path), "--output_dir", str(output_dir)],
            capture_output=True,
            text=True,
            check=True,
            timeout=SUBPROCESS_TIMEOUT,
        )
        
        # 截取标准输出中最后一行作为 JSON 解析
        lines = result.stdout.strip().split('\n')
        json_data = next(line for line in reversed(lines) if line.startswith("{"))
        topology_data = json.loads(json_data)

        job.status = "parsed"
        db.commit()
        
    except subprocess.TimeoutExpired:
        job.status = "failed"
        db.commit()
        raise HTTPException(status_code=504, detail=f"FreeCAD 处理超时 (>{SUBPROCESS_TIMEOUT}s)")
    except Exception as e:
        # **开发备用/测试模式降级 (Mock Fallback)** 
        # 当本地未配置 FreeCAD 环境变量时，走此通道保证可以测试前端交互：
        print(f"[Warning] FreeCAD 执行异常或未找到 (使用 Mock 数据降级处理): {str(e)}")
        # 生成 Mock 方盒 OBJ 让前端 3D 预览仍可用
        mock_obj = _generate_mock_box_obj(50.0, 50.0, 20.0)
        mock_obj_path = output_dir / "mock_model.obj"
        mock_obj_path.write_text(mock_obj)
        topology_data = {
            "features": {"volume": 15000.5, "bbox_x": 50.0, "bbox_y": 50.0, "z_depth": 20.0},
            "faces": [
                {"face_id": 0, "normal": {"x": 0, "y": 0, "z": 1}, "center": {"x": 25, "y": 25, "z": 20}},
                {"face_id": 1, "normal": {"x": 0, "y": 0, "z": -1}, "center": {"x": 25, "y": 25, "z": 0}},
                {"face_id": 2, "normal": {"x": 0, "y": -1, "z": 0}, "center": {"x": 25, "y": 0, "z": 10}},
                {"face_id": 3, "normal": {"x": 0, "y": 1, "z": 0}, "center": {"x": 25, "y": 50, "z": 10}},
                {"face_id": 4, "normal": {"x": -1, "y": 0, "z": 0}, "center": {"x": 0, "y": 25, "z": 10}},
                {"face_id": 5, "normal": {"x": 1, "y": 0, "z": 0}, "center": {"x": 50, "y": 25, "z": 10}},
            ],
            "render_file": "mock_model.obj"
        }
        job.status = "parsed_mock"
        db.commit()
        
    render_file = topology_data.get("render_file")
    render_url = f"/static/{job_id}/{render_file}" if render_file else None

    return {
        "message": "File parsed successfully (Mocked if warning shown)",
        "job_id": job_id,
        "render_url": render_url,
        "topology": topology_data
    }


def _generate_mock_box_obj(sx: float, sy: float, sz: float) -> str:
    """生成一个以原点为角的长方体 OBJ 文本，用于 Mock 模式 3D 预览。"""
    verts = [
        (0, 0, 0), (sx, 0, 0), (sx, sy, 0), (0, sy, 0),
        (0, 0, sz), (sx, 0, sz), (sx, sy, sz), (0, sy, sz),
    ]
    normals = [
        (0, 0, -1), (0, 0, 1),
        (0, -1, 0), (0, 1, 0),
        (-1, 0, 0), (1, 0, 0),
    ]
    # 每个面 2 个三角形, 顶点索引 1-based
    faces = [
        # bottom (z=0)
        (1, 2, 3, 1), (1, 3, 4, 1),
        # top (z=sz)
        (5, 7, 6, 2), (5, 8, 7, 2),
        # front (y=0)
        (1, 6, 2, 3), (1, 5, 6, 3),
        # back (y=sy)
        (3, 8, 4, 4), (3, 7, 8, 4),
        # left (x=0)
        (1, 4, 8, 5), (1, 8, 5, 5),
        # right (x=sx)
        (2, 6, 7, 6), (2, 7, 3, 6),
    ]
    lines = ["# Mock box OBJ generated by Cloud CAM"]
    for v in verts:
        lines.append(f"v {v[0]} {v[1]} {v[2]}")
    for n in normals:
        lines.append(f"vn {n[0]} {n[1]} {n[2]}")
    for f in faces:
        lines.append(f"f {f[0]}//{f[3]} {f[1]}//{f[3]} {f[2]}//{f[3]}")
    return "\n".join(lines) + "\n"
